apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"p, role:admin, applications, *, allow\np, role:admin, clusters, get, allow\np, role:admin, repositories, get, allow\np, role:admin, repositories, create, allow\np, role:admin, repositories, update, allow\np, role:admin, repositories, delete, allow\np, role:admin, apikeys, create, allow\np, role:admin, apikeys, delete, allow\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-03-06T15:16:21Z","labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"6400","uid":"9a96c547-74f5-4228-9e21-9af46f4dd9bb"}}
  creationTimestamp: "2024-03-06T15:16:21Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "14151"
  uid: 9a96c547-74f5-4228-9e21-9af46f4dd9bb
