apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: denis-karpenter-demo
  region: us-west-2
  version: "1.29"
  tags:
    karpenter.sh/discovery: denis-karpenter-demo

vpc:
  id: "vpc-0cdd7534deb879fbc"
  subnets:
    private:
      us-east-1a: { id: "subnet-0f647d7e3a075627d" }
      us-east-1b: { id: "subnet-042a68fbff9f8d2b0" }

iam:
  withOIDC: true
  podIdentityAssociations:
  - namespace: "kube-system"
    serviceAccountName: karpenter
    roleName: denis-karpenter-demo-karpenter
    permissionPolicyARNs:
    - arn:aws:iam::917024903431:policy/KarpenterControllerPolicy-denis-karpenter-demo

iamIdentityMappings:
- arn: "arn:aws:iam::917024903431:role/KarpenterNodeRole-denis-karpenter-demo"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes


managedNodeGroups:
- instanceType: t4g.small
  amiFamily: AmazonLinux2
  name: denis-karpenter-demo-ng
  desiredCapacity: 1
  minSize: 1
  maxSize: 2
  privateNetworking: true
  subnets:
    - "subnet-0f647d7e3a075627d"
    - "subnet-042a68fbff9f8d2b0"

addons:
- name: eks-pod-identity-agent
